accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
]

employee/urls.py
from django.urls import path
from . import views


app_name = 'employee'
urlpatterns = [
    path('', views.index, name='index'),
    path('login_index/', views.login_index, name='login_index'),
    path('ex/', views.ex, name='ex'),
    path('law', views.law, name='law'),
    path('quiz/', views.quiz, name='quiz'),
    path('study/', views.study, name='study'),          # 메인 스터디 페이지
    path('<int:pk>/', views.lecture, name='lecture'),   # 특정 강의
    path('<int:pk>/test/', views.test, name='test'),    # 특정 강의에 대한 테스트
    path('<username>/', views.suggestion, name= 'suggestion'),   # 안전관리 제언
]

manager/urls.py
from django.urls import path
from . import views


app_name = 'manager'
urlpatterns = [
    path('<username>/', views.index, name='index'),
    path('<username>/scanner/', views.scanner, name='scanner'),
    path('<username>/create/', views.create, name='create'),
]

safety_manager/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index),
    path('admin/', admin.site.urls),
    path('employee/', include('employee.urls')),
    path('manager/', include('manager.urls')),
    path('accounts/', include('accounts.urls')),
    path('suggestions/', include('suggestions.urls')),
    path('complain/', include('complain.urls'))
]

suggestions/urls.py
from django.urls import path
from . import views


app_name = 'suggestions'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/comments/', views.comment_create, name='comment_create'),
    path('<int:suggestion_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
]

suggestions/models.py
from django.db import models
from django.conf import settings

# Create your models here.
# pk name title content image
class Suggestion(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(blank=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    STATUS_CHOICES = (
        ('1', '처리중'),
        ('2', '반려'),
        ('3', '처리완료'),
    )
    suggestion = models.OneToOneField(Suggestion, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES)
    reason = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.status

suggestions/forms.py
from django import forms
from .models import Suggestion, Comment


class SuggestionForm(forms.ModelForm):

    class Meta:
        model = Suggestion
        exclude = ('user', )


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('status', 'reason')

suggestions/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_http_methods, require_POST, require_safe
from .models import Suggestion, Comment
from .forms import SuggestionForm, CommentForm

# Create your views here.
@require_safe
def index(request):
    suggestions = Suggestion.objects.order_by('-pk')
    context = {
        'suggestions': suggestions,
    }
    print(dir(suggestions))
    return render(request, 'suggestions/index.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == 'POST':
        form = SuggestionForm(request.POST)
        if form.is_valid():
            suggestion = form.save(commit=False)
            suggestion.user = request.user
            suggestion.save()
            return redirect('suggestions:detail', suggestion.pk)
    else:
        form = SuggestionForm()
    context = {
        'form': form,
    }
    return render(request, 'suggestions/create.html', context)


@require_safe
def detail(request, pk):
    suggestion = get_object_or_404(Suggestion, pk=pk)
    comment_form = CommentForm()
    context = {
        'suggestion': suggestion,
        'comment_form': comment_form,
    }
    return render(request, 'suggestions/detail.html', context)


@require_POST
def delete(request, pk):
    suggestion = get_object_or_404(Suggestion, pk=pk)
    if request.user.is_authenticated:
        if request.user == suggestion.user:
            suggestion.delete()
    return redirect('suggestions:index')


@login_required
@require_http_methods(['GET', 'POST'])
def update(request, pk):
    suggestion = get_object_or_404(Suggestion, pk=pk)
    if request.user == suggestion.user:
        if request.method == 'POST':
            form = SuggestionForm(request.POST, instance=suggestion)
            if form.is_valid():
                suggestion = form.save()
                return redirect('suggestions:detail', suggestion.pk)
        else:
            form = SuggestionForm(instance=suggestion)
    else:
        return redirect('suggestions:index')
    context = {
        'suggestion': suggestion,
        'form': form,
    }
    return render(request, 'suggestions/update.html', context)


@require_POST
def comment_create(request, pk):
    if request.user.is_authenticated:
        suggestion = get_object_or_404(Suggestion, pk=pk)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.suggestion = suggestion
            comment.user = request.user
            comment.save()
        return redirect('suggestions:detail', suggestion.pk)
    return redirect('accounts:login')


@require_POST
def comment_delete(request, suggestion_pk ,comment_pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=comment_pk)
        if request.user == comment.user:
            comment.delete()
    return redirect('suggestions:detail', suggestion_pk)

suggestions/templates/suggestions/create.html
{% extends 'base.html' %}

{% block content %}
  <div class="card p-4" >
    <h1>안전 제언</h1>
    <hr>
    <form action="{% url 'suggestions:create' %}" method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" class="btn btn-primary mt-4">
      <a href="{% url 'suggestions:index' %}" class="btn btn-secondary mt-4">뒤로 가기</a>
    </form>
  </div>
{% endblock content %}

suggestions/templates/suggestions/detail.html
{% extends 'base.html' %}

{% block content %}
<div class="card p-4" >
  <h1>상세 내용</h1>
  
  <hr>
  <p>제목 : {{ suggestion.title }}</p>
  <p>내용 : {{ suggestion.content }}</p>
  <p>작성 시각 : {{ suggestion.created_at }}</p>
  <p>수정 시각 : {{ suggestion.updated_at }}</p>
  <hr>
  {% if request.user == suggestion.user %}
    
    <form action="{% url 'suggestions:delete' suggestion.pk %}" method="POST" >
      {% csrf_token %}
      <a href="{% url 'suggestions:update' suggestion.pk %}" class="btn btn-primary">수정</a>
      <input type="submit" value="삭제" class="btn btn-danger">
    </form>
  {% endif %}
  
  <hr>
  
  <ul>
    {% if suggestion.comment %}
      <li>
        {% if suggestion.comment.status == "1" %}
          <p style="color: yellow;">처리중</p>
        {% elif suggestion.comment.status == "2" %}
          <p style="color: red;">반려</p>
        {% else %}
          <p style="color: green;">처리완료</p>
        {% endif %}
        <p>반려 사유 : {{ suggestion.comment.reason }}</p> 

        {% if request.user == comment.user %}
          <form action="{% url 'suggestions:comment_delete' suggestion.pk comment.pk %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="삭제">
          </form>
        {% endif %}
      </li>
    
  </ul>
  <hr>
  <a href="{% url 'suggestions:index' %}" class="btn btn-secondary mt-4">뒤로 가기</a>
  {% else %}
    {% if request.user.is_authenticated %}
      <form action="{% url 'suggestions:comment_create' suggestion.pk %}" method="POST">
        {% csrf_token %}
        {{ comment_form }}
        <input type="submit">
      </form>
    {% else %}
      <a href="{% url 'accounts:login' %}">[댓글을 작성하려면 로그인하세요.]</a>
    {% endif %}
  {% endif %}
</div>
{% endblock content %}

suggestions/templates/suggestions/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>나의 안전 제언</h1>
  {% if request.user.is_authenticated %}
    <button type="button" class="btn btn-primary my-4">
      <a href="{% url 'suggestions:create' %}" style="color: white; text-decoration: none;">제안하기</a>
    </button><br/>
  {% else %}
    <a href="{% url 'accounts:login' %}">[새 글을 작성하려면 로그인 하세요]</a>
  {% endif %}
  <hr>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">상태</th>
        <th scope="col">제목</th>
        <th scope="col">상세 내용</th>
      </tr>
    </thead>
    <tbody>
      {% for suggestion in suggestions %}
        <tr>
          <th>{{ suggestion.pk }}</th>
          {% if suggestion.comment.status == "1" %}
            <td style="color: yellow;">처리중</td>
          {% elif suggestion.comment.status == "2" %}
            <td style="color: red;">반려</td>
          {% else %}
            <td style="color: green;">처리완료</td>
          {% endif %}
          <td>{{ suggestion.title }}</td>
          <td><a href="{% url 'suggestions:detail' suggestion.pk %}">상세 내용</a></td>
        </tr>
      {% endfor %}
    </tbody>
</table>
<a href="{% url 'employee:index' %}" class="btn btn-secondary mt-4">뒤로 가기</a>
  

  {% comment %} {% for suggestion in suggestions %}
    {% if suggestion.comment.status == "1" %}
      <p style="color: yellow;">처리중</p>
    {% elif suggestion.comment.status == "2" %}
      <p style="color: red;">반려</p>
    {% else %}
      <p style="color: green;">처리완료</p>
    {% endif %}
    <p>글 제목: {{ suggestion.title }}</p>
    <p>글 내용: {{ suggestion.content }}</p>
    <a href="{% url 'suggestions:detail' suggestion.pk %}">상세 내용</a>
    <hr>
  {% endfor %} {% endcomment %}
{% endblock content %}

suggestions/templates/suggestions/update.html
{% extends 'base.html' %}

{% block content %}
  <h1>UPDATE</h1>
  <hr>
  <form action="{% url 'suggestions:update' suggestion.pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
  <a href="{% url 'suggestions:detail' suggestion.pk %}">back</a>
{% endblock content %}