complain/urls.py
from django.urls import path
from . import views


app_name = 'complain'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/comments/', views.comment_create, name='comment_create'),
    path('<int:complain_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
]

employee/urls.py
from django.urls import path
from . import views


app_name = 'employee'
urlpatterns = [
    path('', views.index, name='index'),
    path('login_index/', views.login_index, name='login_index'),
    path('ex/', views.ex, name='ex'),
    path('law', views.law, name='law'),
    path('quiz/', views.quiz, name='quiz'),
    path('study/', views.study, name='study'),          # 메인 스터디 페이지
    path('<int:pk>/', views.lecture, name='lecture'),   # 특정 강의
    path('<int:pk>/test/', views.test, name='test'),    # 특정 강의에 대한 테스트
    path('<username>/', views.suggestion, name= 'suggestion'),   # 안전관리 제언
]

manager/urls.py
from django.urls import path
from . import views


app_name = 'manager'
urlpatterns = [
    path('<username>/', views.index, name='index'),
    path('<username>/scanner/', views.scanner, name='scanner'),
    path('<username>/create/', views.create, name='create'),
]

safety_manager/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index),
    path('admin/', admin.site.urls),
    path('employee/', include('employee.urls')),
    path('manager/', include('manager.urls')),
    path('accounts/', include('accounts.urls')),
    path('suggestions/', include('suggestions.urls')),
    path('complain/', include('complain.urls'))
]

suggestions/urls.py
from django.urls import path
from . import views


app_name = 'suggestions'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/comments/', views.comment_create, name='comment_create'),
    path('<int:suggestion_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
]

employee/models.py
from django.db import models

# Create your models here.
class StudyList(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

employee/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required

from django.shortcuts import render, redirect, get_object_or_404

from django.views.decorators.http import require_http_methods, require_POST, require_safe
from employee.models import StudyList

# Create your views here.
# 작업자들이 들어가면 보게 될 메인 화면

@login_required
def index(request):
    return render(request, 'employee/index.html')

@login_required
def login_index(request):
    return render(request, 'employee/login_index.html')

@login_required
def ex(request):
    return render(request, 'employee/ex.html')

@login_required
def law(request):
    return render(request, 'employee/law.html')

@login_required
def quiz(request):
    return render(request, 'employee/quiz.html')

# 모든 강의 목록, 최신 순으로 나열
@login_required
def study(request):
    lectures = StudyList.objects.order_by('-pk')
    context = {
        'lectures': lectures,
    }
    return render(request, 'employee/study.html', context)

# 강의 - 글이나 영상을 미리 DB에 넣어놔야 가져올 것 같은데??
@login_required
def lecture(request, pk):
    lecture = get_object_or_404(StudyList, pk=pk)
    context = {
        'lecture': lecture,
    }
    return render(request, 'employee/lecture.html', context)

# 시험 - 시험 페이지는 HTML로 작성되어야 할 것 같은데...??
@login_required
def test(request, pk):
    return render(request, 'employee/test.html')

# 입출결 - QR코드 생성
@login_required
def suggestion(request, username):
    person = get_object_or_404(get_user_model(), username=username) # user 이름으로 넘기면 될듯
    context ={
        'person' : person,
    }
    return render(request, 'employee/suggestion.html', context)
    

employee/templates/employee/ex.html
{% extends 'base.html' %}
{% block content %}
    <p class="h3">사망사고사례</p>
    <table class="table">
        <thead>
          <tr>
            <th scope="col"></th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row ">사고명</th>
            <td>고양향동 지원 4BL 손가락 골절사고</td>

          </tr>
          <tr>
            <th scope="row">발생 일시</th>
            <td>2022-06-07 오후 03:20</td>

          </tr>
          <tr>
            <th scope="row">사고 경위</th>
            <td>2022년 06 07일 오후 3시 20분경 재해자 성**씨는 동료인 최**씨와 함께 1층 기둥 거푸집 해체작업중 최**씨가 해체한 기둥밴드가 보거푸집 지지와이어로 떨어지면서 반대편에서 해체작업 대기 중이던 재해자 성**씨의 왼쪽 손이 보거푸집 지지 와이어에 부딪치면서 좌측 5번쨰 손가락의 근위지골골절 및 약지손가락이 찢어지는 사고</td>

          </tr>
        </tbody>
      </table>
    <a href="{% url 'employee:quiz' %}" style="text-decoration: none;" class="btn btn-primary">다음으로</a>
    <a href="{% url 'employee:index' %}" style="text-decoration: none;" class="btn btn-secondary mx-2">뒤로 가기</a>
{% endblock content %}

employee/templates/employee/index.html
{% extends 'base_login.html' %}
{% load qr_code %}

{% block content %}

  {% comment %} <div class="w-100 my-5" >
    <img src="https://media.istockphoto.com/photos/safety-construction-worker-hats-blue-white-yellow-orange-teamwork-of-picture-id1205863144?k=20&m=1205863144&s=612x612&w=0&h=BxkJXCFWIe-jrHQopkDYDg8ymT0lssD1fEbbiCeCZz4=" alt="" style="object-fit: cover; width: 100%">
  </div> {% endcomment %}

  <div class="container">

    <div class="d-flex flex-column justify-content-center align-items-center">
      <!-- Modal -->
      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="myInput" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="myInput">경고</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              작업 중지권이 발동되었습니다!<br> 관리자의 지시가 있을떄까지 대기하여 주십시오.
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-danger" data-bs-dismiss="modal">확인했습니다</button>
            </div>
          </div>
        </div>
      </div>
  
      <div class="row ">
        <div class="col-sm-6 mb-4">
          <div class="card" style="background-image: url('https://t3.ftcdn.net/jpg/02/09/41/14/240_F_209411468_y0WbvUOYwSddmRhdXX2MKDlyiACemtib.jpg'); background-size: 100%;">
            <a href="{% url 'employee:ex' %}" style="color: black; text-decoration: none;">
              <div class="card-body">
                <h5 class="card-title">출력 등록&nbsp ></h5>
                <hr>
                <p class="card-text">QR 코드 출근을 찍기 위해 사고 사례를 보고 문제를 풉니다.</p><br>
              </div>
            </a>  
          </div>
        </div>
        <div class="col-sm-6 mb-4">
          <div class="card" style="background-image: url('https://t4.ftcdn.net/jpg/01/68/55/41/240_F_168554180_rT3GO4tcgl6c1m1mpTPnkoBEvtkaHoIz.jpg'); background-size: 100%;">
            <a href="{% url 'suggestions:index' %}" style="color: black; text-decoration: none;">
              <div class="card-body">
                <h5 class="card-title">안전 신문고&nbsp ></h5>
                <hr>
                <p class="card-text">현장의 무사고를 위해, 동료를 위해 불안한 상황을 제보해 주세요.</p><br>
              </div>
            </a>
          </div>
        </div>
        <div class="col-sm-6 mb-4">
          <div class="card" style="border: none; color: white; background-image: url('https://media.istockphoto.com/photos/miner-in-a-yellow-hard-hat-on-a-black-background-dirty-with-coal-dust-picture-id1352297658?k=20&m=1352297658&s=612x612&w=0&h=zwMPzcw8MM15t8j3nlCwHJRJc40gXg5E8BNBTom2_qc=');">
            <div class="card-body">
              <h5 class="card-title">자기 보호권&nbsp ></h5>
              <hr>
              <p class="card-text">불안한 상황에서 일을 강요받거나, 사고가 당장이라도 날 것 같으면 신고해주시고 작업을 모두 멈춰주세요.</p>
              <div style="text-align: right;">
                <button type="button" class="btn btn-danger" style="width: 160px" data-bs-toggle="modal" data-bs-target="#exampleModal">
                  작업 중지권 발동&nbsp >
                </button>
              </div>
            </div>
          </div>
        </div>
        {% if user.user_type > "2" %}
        <div class="col-sm-12 mb-4">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">QR코드 스캔</h5>
              <hr>
              <p class="card-text">관리자라면 출근 등록을 진행하기 위해서 큐알 코드 스캔을 진행해 주세요</p>
              <a href="{% url 'manager:index' request.user.username %}" style="color: white; text-decoration: none;" class="btn btn-primary">QR 코드 스캔</a>
            </div>
          </div>
        </div>
        {% endif %}
      </div>
      <div style="width: 75px; height: 75px; border-radius: 50px; position: fixed; bottom: 30px; right: 30px; background: white;">
        <div class="d-flex justify-content-center align-items-center" style="height: 100%">
          <div style="text-align: center">
            <a href="{% url 'complain:index' %}" >
                <img src="https://cdn-icons-png.flaticon.com/128/596/596092.png" alt="" style="width: 50%; height: 50%; border-radius: 50px" >
            </a>
          </div>
        </div>
      </div>
      <script>
        const myModal = document.getElementById('myModal')
        const myInput = document.getElementById('myInput')
  
        myModal.addEventListener('shown.bs.modal', () => {
          myInput.focus()
        })
      </script>
    </div>
  </div>
{% endblock content %}

employee/templates/employee/law.html
{% extends 'base.html' %}
{% block content %}
    <p>관련 법률</p>
    <a href="{% url 'employee:ex' %}" style="text-decoration: none;">< 뒤로</a>
    <a href="{% url 'employee:quiz' %}" style="text-decoration: none;">다음으로 ></a>
{% endblock content %}

employee/templates/employee/login_index.html
{% extends 'base_login.html' %}
{% load qr_code %}

{% block content %}

  {% comment %} <div class="w-100 my-5" >
    <img src="https://media.istockphoto.com/photos/safety-construction-worker-hats-blue-white-yellow-orange-teamwork-of-picture-id1205863144?k=20&m=1205863144&s=612x612&w=0&h=BxkJXCFWIe-jrHQopkDYDg8ymT0lssD1fEbbiCeCZz4=" alt="" style="object-fit: cover; width: 100%">
  </div> {% endcomment %}

  <div class="d-flex flex-column justify-content-center align-items-center">
     <div>
      <p class="h3 text-center">출근 QR 코드</p>
      <p>{% qr_from_text user.name size=20 border=6 %}</p>
    </div>
  </div>
  <div class="container">

    <div class="row ">
   
      <div class="col-sm-12 mb-4">
        <div class="card" style="background-image: url('https://t4.ftcdn.net/jpg/01/68/55/41/240_F_168554180_rT3GO4tcgl6c1m1mpTPnkoBEvtkaHoIz.jpg'); background-size: 100%;">
          <a href="{% url 'suggestions:index' %}" style="color: black; text-decoration: none;">
            <div class="card-body">
              <h5 class="card-title">안전 신문고&nbsp ></h5>
              <hr>
              <p class="card-text">현장의 무사고를 위해, 동료를 위해 불안한 상황을 제보해 주세요.</p><br>
            </div>
          </a>
        </div>
      </div>
      <div class="col-sm-12 mb-4">
        <div class="card" style="border: none; color: white; background-image: url('https://media.istockphoto.com/photos/miner-in-a-yellow-hard-hat-on-a-black-background-dirty-with-coal-dust-picture-id1352297658?k=20&m=1352297658&s=612x612&w=0&h=zwMPzcw8MM15t8j3nlCwHJRJc40gXg5E8BNBTom2_qc=');">
          <div class="card-body">
            <h5 class="card-title">자기 보호권&nbsp ></h5>
            <hr>
            <p class="card-text">불안한 상황에서 일을 강요받거나, 사고가 당장이라도 날 것 같으면 신고해주시고 작업을 모두 멈춰주세요.</p>
            <div style="text-align: right;">
              <button type="button" class="btn btn-danger" style="width: 160px" data-bs-toggle="modal" data-bs-target="#exampleModal">
                작업 중지권 발동&nbsp >
              </button>
            </div>
          </div>
        </div>
      </div>

      {% if user.user_type > "2" %}
      <div class="col-sm-12 mb-4">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">QR코드 스캔</h5>
            <hr>
            <p class="card-text">관리자라면 출근 등록을 진행하기 위해서 큐알 코드 스캔을 진행해 주세요</p>
            <a href="{% url 'manager:index' request.user.username %}" style="color: white; text-decoration: none;" class="btn btn-primary">QR 코드 스캔</a>
          </div>
        </div>
      </div>
      {% endif %}
      <div style="width: 75px; height: 75px; border-radius: 50px; position: fixed; bottom: 30px; right: 30px; background: white;">
        <div class="d-flex justify-content-center align-items-center" style="height: 100%">
          <div style="text-align: center">
            <a href="{% url 'complain:index' %}" >
                <img src="https://cdn-icons-png.flaticon.com/128/596/596092.png" alt="" style="width: 50%; height: 50%; border-radius: 50px" >
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

employee/templates/employee/push.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script type="module">
        // Import the functions you need from the SDKs you need
        import { initializeApp } from "https://www.gstatic.com/firebasejs/9.8.3/firebase-app.js";
        import { getAnalytics } from "https://www.gstatic.com/firebasejs/9.8.3/firebase-analytics.js";
        // TODO: Add SDKs for Firebase products that you want to use
        // https://firebase.google.com/docs/web/setup#available-libraries
      
        // Your web app's Firebase configuration
        // For Firebase JS SDK v7.20.0 and later, measurementId is optional
        const firebaseConfig = {
          apiKey: "AIzaSyCcQWFSToc9-tQY2Vqw4qgwa2QMm105FP0",
          authDomain: "safety-429ae.firebaseapp.com",
          projectId: "safety-429ae",
          storageBucket: "safety-429ae.appspot.com",
          messagingSenderId: "879415531555",
          appId: "1:879415531555:web:efbff78b7426a319b8b996",
          measurementId: "G-Y0V5E7MXW8"
        };
      
        // Initialize Firebase
        const app = initializeApp(firebaseConfig);
        const analytics = getAnalytics(app);
      </script>
</body>
</html>

employee/templates/employee/quiz.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <style>
        .quiz-container{
            position:relative;
            background-color:#f8f6f0;
            font-size:17px;
            color:#333;
            height:150px;
            margin-top:40px;
            text-align:center;
            font-weight:300;
        }
        
        .slide{
           position:absolute;
           left:0px;
           top:40px;
           width:100%;
           z-index:1;
           opacity:0;
           transition:opacity 0.5s;
        }
        
        .active-slide{
           opacity:1;
           z-index:2;
        }
    </style>
    <title>Document</title>
</head>
<body>
    <div class="container">
        <div class="mt-4 mb-4">
            <h1 >근로자 출력등록2</h1>
        </div>
        <div class="card p-5">
            <p>제3조(전도의 방지)</p>
            <p>#안전보건규칙 #제2장 #작업장 #전도 #청결 #근로자</p>
            <div class="quiz-container">
                <div id="quiz"> </div>
            </div>
            
            <div class="quiz-ctrl">
                <button id="next" class="quiz-btn btn btn-primary mt-4"> 다음 문제 </button>
                <button id="submit" class="quiz-btn btn btn-info mt-4 mx-2"> 결과확인 </button>
                <button id="previous" class="quiz-btn btn btn-secondary mt-4"> 이전 문제 </button>
               <div id="result" class="text-center"> </div>
            </div>
        </div>
        <a href="{% url 'employee:login_index' %}" id="move" style="display: none;" class="btn btn-info mt-4">출근 등록</a>
        <a href="{% url 'employee:ex' %}" style="text-decoration: none;" class="btn btn-secondary mt-4">메인으로</a>
    </div>


    <script>
        const quizData = [
            {
                question : '1. 사업주는 근로자가 작업장에서 넘어지거나 미끄러지는 등의 위험이 없도록 작업장 바닥등을 ___________로 유지하여야 한다.',
                answers : {
                    a : "안전하고 청결한 상태",
                    b : "정리되지 않고 더러운",
                },
                correct : 'a'
            },
            {
                question : '2. 사업주는 제품, 자재, 부재 등이 ___________ 붙들어 지탱하게 하는 등 안전 조치를 하여야 한다. 다만, 근로자가 접근하지 못하도록 조치한 경우에는 그러지 아니하다.',
                answers : {
                    a : "넘어질 수 있도록",
                    b : "넘어지지 않도록",
                },
                correct : 'b'
            },
        ]
        
        const quizDisplay = document.getElementById('quiz');
        const submitBtn = document.getElementById('submit');
        const previousBtn = document.getElementById('previous');
        const nextBtn = document.getElementById('next');

        let currentSlide = 0;
        const resultDisplay = document.getElementById('result');
        const moveDisplay = document.getElementById('move');
        
        function buildQuiz(){
            let output = [ ]; 
            quizData.forEach(  
                (currentQuestion, questionNum) => { 
                            const answers = [ ];     
                            for(item in currentQuestion.answers){  
                                        answers.push(`<label>
                                                        <input type="radio" name="question${questionNum}" value="${item}">
                                                            ${item} : ${currentQuestion.answers[item]}
                                                        </label>`);
                                }
                                    output.push(`<div class="slide"><div class="question"> ${currentQuestion.question}</div>
                                                <div class="answer">${answers.join('&nbsp;&nbsp;&nbsp;&nbsp;')}</div></div>`);
                            }              
            );
                quizDisplay.innerHTML = output.join('</br>');
            }
            
        function showResult(){
                const answerDisplays = quizDisplay.querySelectorAll('.answer');  
                let numCorrect = 0; 

                    quizData.forEach( (currentQuestion, questionNum)=>{
                        const answerDisplay = answerDisplays[questionNum]; 
                        const selector = `input[name=question${questionNum}]:checked`;  
                        const userAnswer = (answerDisplay.querySelector(selector) || {}).value;  


                            if(userAnswer === currentQuestion.correct){    
                                    numCorrect++;
                                    answerDisplays[questionNum].style.color = 'lightgreen';
                            }else{
                                    answerDisplays[questionNum].style.color = 'red';
                            }
                    });
                        
                    
                    submitBtn.style.display = 'none';
                    resultDisplay.innerHTML = `<h3 style="color:#333;">${quizData.length}개중에서 ${numCorrect}개 맞추셨습니다.</h3>`
                    if (numCorrect == 2) {
                        moveDisplay.style.display = 'block';
                    }
            }
        
            
        function showSlide(n){
            slides[currentSlide].classList.remove('active-slide');
            slides[n].classList.add('active-slide');
            currentSlide = n;
            if(currentSlide === 0){
                previousBtn.style.display = 'none';
            }else{
                previousBtn.style.display = 'inline-block';
            }
            if(currentSlide === slides.length-1){
                nextBtn.style.display = 'none';
                submitBtn.style.display = 'inline-block';
            }else{
                nextBtn.style.display = 'inline-block';
                submitBtn.style.display = 'none';
                    if(document.getElementById('retry')){
                            document.getElementById('retry').style.display = 'none';
                        }
                
            }
        }

        function showNextSlide(){  showSlide(currentSlide+1); }
        function showPreviousSlide(){ showSlide(currentSlide-1); }

        
        buildQuiz(); 
        const slides = document.querySelectorAll('.slide');
        showSlide(currentSlide);
        previousBtn.addEventListener('click',showPreviousSlide);
        nextBtn.addEventListener('click',showNextSlide);
        submitBtn.addEventListener('click',showResult);   
    </script>
</body>
</html>

employee/templates/employee/study.html
{% extends 'base.html' %}

{% block content %}
  <style>
    .red {
      color: red;
    }
  </style>
  <h1>employee</h1>
  
  <p>1. 강의 내용</p>

  <p>2. 시험 보기</p>
  
  <ol>
    <li>일단은 study1, 2, 3, ... 10 만들어서 선택하게 하고 추후에 스터디를 pk로 가지게 해서 동적으로 변경</li>
    <li>강의 내용 밑에 테스트 두기</li>
    <li>테스트에 통과하면 다음 페이지로 넘어가기</li>
    <li>다음 페이지로 넘어가서 QR체크인</li>
    <li>추후에 RESTfulAPI로 변경?? 아직은 AJAX까진 필요 없을듯?? => 속도 우선순위</li>
  <ol>
  <br><br>
  <h3>아래의 내용을 보완할 방법으로, 빈 칸에 들어갈 적절한 단어를 골라주세요</h3>
  <p>건축물 보관창고 지붕에 올라 비닐천막을 씌우고 이동하던 중 잘못 밟은 채광창이 깨지면서 약 5.4m 바닥으로 떨어져 사망</p>
  <ul class="d-flex justify-content-between align-items-center">
    <div>
      <!--만약 problem1이 정답이면 다음문제로-->
      <li>폭 [<span id="problem1"></span>] 이상의 발판 혹은 안전방망 설치</li> 
      <hr>
      <li>지붕 위에서 떨어짐 [<span id="problem2"></span>] 실시</li>
      <hr>
      <li>안전대 [<span id="problem3"></span>] 설치 및 안전대, 안전모 등 보호구 착용</li>
    </div>
    <div>
      <ul>
        <li><button id="button1">30cm 이상</button></li>
        <hr>
        <li><button id="button2">부착설비</button></li>
        <hr>
        <li><button id="button3">위험방지 조치</button></li>
      </ul>
    </div>
  </ul>
  
      
  <hr>
  <a href="{% url 'employee:index' %}">뒤로 가기</a>
  
  <script>
    const problem1 = document.querySelector('#problem1')
    const problem2 = document.querySelector('#problem2')
    const problem3 = document.querySelector('#problem3')
    const button1 = document.querySelector('#button1')
    const button2 = document.querySelector('#button2')
    const button3 = document.querySelector('#button3')
    
    button1.addEventListener('click', function(event) {
      problem1.innerText = button1.innerText
      if (problem1.innerText !== "30cm 이상") {
        problem1.setAttribute('class', 'red')
      }
      button1.innerText = ""
    })
    button2.addEventListener('click', function(event) {
      problem2.innerText = button2.innerText
      if (problem2.innerText !== "위험방지 조치") {
        problem2.setAttribute('class', 'red')
      }
      button2.innerText = ""
    })
    button3.addEventListener('click', function(event) {
      problem3.innerText = button3.innerText
      if (problem3.innerText !== "부착설비") {
        problem3.setAttribute('class', 'red')
      }
      button3.innerText = ""
    })
    // 처음 상태에서는 문제1에 포커스
    // 맞은문제 알람
    // 체크 후 문제2에 (순서대로) 포커스

    // 수정해야 할 사항
    // 누른 버튼이 답으로 들어가게 하고, 원래 들어가야할 답과 비교해서 맞으면 정답체크
    // 틀리면 오답 표시 후 특정 부분 다시 렌더링(새로고침)
    
  </script>
{% endblock content %}