accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
]

complain/urls.py
from django.urls import path
from . import views


app_name = 'complain'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/comments/', views.comment_create, name='comment_create'),
    path('<int:complain_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
]

employee/urls.py
from django.urls import path
from . import views


app_name = 'employee'
urlpatterns = [
    path('', views.index, name='index'),
    path('login_index/', views.login_index, name='login_index'),
    path('ex/', views.ex, name='ex'),
    path('law', views.law, name='law'),
    path('quiz/', views.quiz, name='quiz'),
    path('study/', views.study, name='study'),          # 메인 스터디 페이지
    path('<int:pk>/', views.lecture, name='lecture'),   # 특정 강의
    path('<int:pk>/test/', views.test, name='test'),    # 특정 강의에 대한 테스트
    path('<username>/', views.suggestion, name= 'suggestion'),   # 안전관리 제언
]

manager/urls.py
from django.urls import path
from . import views


app_name = 'manager'
urlpatterns = [
    path('<username>/', views.index, name='index'),
    path('<username>/scanner/', views.scanner, name='scanner'),
    path('<username>/create/', views.create, name='create'),
]

safety_manager/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index),
    path('admin/', admin.site.urls),
    path('employee/', include('employee.urls')),
    path('manager/', include('manager.urls')),
    path('accounts/', include('accounts.urls')),
    path('suggestions/', include('suggestions.urls')),
    path('complain/', include('complain.urls'))
]

complain/models.py
from django.db import models
from django.conf import settings

# Create your models here.
# pk name title content image
class Complain(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class ComplainComment(models.Model):
    complain = models.OneToOneField(Complain, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=10)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.status

complain/forms.py
from django import forms
from .models import Complain, ComplainComment


class ComplainForm(forms.ModelForm):

    class Meta:
        model = Complain
        exclude = ('user', )


class ComplainCommentForm(forms.ModelForm):

    class Meta:
        model = ComplainComment
        fields = ('title', 'content')

complain/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_http_methods, require_POST, require_safe
from .models import Complain, ComplainComment
from .forms import ComplainForm, ComplainCommentForm

# Create your views here.
@require_safe
def index(request):
    complains = Complain.objects.order_by('-pk')
    context = {
        'complains': complains,
    }
    return render(request, 'complains/index.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == 'POST':
        form = ComplainForm(request.POST)
        if form.is_valid():
            complain = form.save(commit=False)
            complain.user = request.user
            complain.save()
            return redirect('complain:detail', complain.pk)
    else:
        form = ComplainForm()
    context = {
        'form': form,
    }
    return render(request, 'complains/create.html', context)


@require_safe
def detail(request, pk):
    complain = get_object_or_404(Complain, pk=pk)
    comment_form = ComplainCommentForm()
    context = {
        'complain': complain,
        'comment_form': comment_form,
    }
    return render(request, 'complains/detail.html', context)


@require_POST
def delete(request, pk):
    complain = get_object_or_404(Complain, pk=pk)
    if request.user.is_authenticated:
        if request.user == complain.user:
            complain.delete()
    return redirect('complain:index')


@login_required
@require_http_methods(['GET', 'POST'])
def update(request, pk):
    complain = get_object_or_404(Complain, pk=pk)
    if request.user == complain.user:
        if request.method == 'POST':
            form = ComplainForm(request.POST, instance=complain)
            if form.is_valid():
                complain = form.save()
                return redirect('complain:detail', complain.pk)
        else:
            form = ComplainForm(instance=complain)
    else:
        return redirect('complain:index')
    context = {
        'complain': complain,
        'form': form,
    }
    return render(request, 'complains/update.html', context)


@require_POST
def comment_create(request, pk):
    if request.user.is_authenticated:
        complain = get_object_or_404(Complain, pk=pk)
        comment_form = ComplainCommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.complain = complain
            comment.user = request.user
            comment.save()
        return redirect('complain:detail', complain.pk)
    return redirect('accounts:login')


@require_POST
def comment_delete(request, complain_pk ,comment_pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(ComplainComment, pk=comment_pk)
        if request.user == comment.user:
            comment.delete()
    return redirect('complain:detail', complain_pk)

complain/templates/complains/create.html
{% extends 'base.html' %}

{% block content %}
<div class="card p-4" >
  <h1>건의하기</h1>
  <hr>
  <form action="{% url 'complain:create' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="건의하기" class="btn btn-primary me-2 mt-4" >
    <a href="{% url 'complain:index' %}" class="btn btn-secondary mt-4">뒤로 가기</a>
  </form>
</div>
{% endblock content %}

complain/templates/complains/detail.html
{% extends 'base.html' %}

{% block content %}
<div class="card p-4" >
  <h1>나의 건의</h1>
  <hr>
  <p>제목 : {{ complain.title }}</p>
  <p>내용 : {{ complain.content }}</p>
  <p>작성 시각 : {{ complain.created_at }}</p>
  <p>수정 시각 : {{ complain.updated_at }}</p>
  <hr>
  {% if request.user == complain.user %}
    <a href="{% url 'complain:update' complain.pk %}">수정</a>
    <form action="{% url 'complain:delete' complain.pk %}" method="POST">
      {% csrf_token %}
      <input type="submit" value="삭제">
    </form>
  {% endif %}
  
  
  <ul>
    
    {% if complain.comment %}
    <hr>
      <li>
        {% if complain.comment.status == "1" %}
          <p style="color: yellow;">처리중</p>
        {% elif complain.comment.status == "2" %}
          <p style="color: red;">반려</p>
        {% else %}
          <p style="color: green;">처리완료</p>
        {% endif %}
        <p>반려 사유 : {{ complain.comment.reason }}</p> 

        {% if request.user == comment.user %}
          <form action="{% url 'complain:comment_delete' complain.pk comment.pk %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="삭제">
          </form>
        {% endif %}
      </li>
  </ul>
  <hr>
  {% endif %}
  <a href="{% url 'complain:index' %}" class="btn btn-secondary mt-4">뒤로 가기</a>
</div>
{% endblock content %}

complain/templates/complains/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>시스템 불편 사항</h1>
  {% if request.user.is_authenticated %}
    <button type="button" class="btn btn-primary my-4">
      <a href="{% url 'complain:create' %}" style="color: white; text-decoration: none;">제안하기</a>
    </button><br/>
  {% else %}
    <a href="{% url 'accounts:login' %}">[새 글을 작성하려면 로그인 하세요]</a>
  {% endif %}
  <hr>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">상태</th>
        <th scope="col">제목</th>
        <th scope="col">상세 내용</th>
      </tr>
    </thead>
    <tbody>
      {% for complain in complains %}
        <tr>
          <th>{{ complain.pk }}</th>
          <td>{{ complain.title }}</td>
          <td><a href="{% url 'complain:detail' complain.pk %}">상세 내용</a></td>
        </tr>
      {% endfor %}
    </tbody>
</table>
<a href="{% url 'employee:index' %}" class="btn btn-secondary mt-4">뒤로 가기</a>
{% endblock content %}

complain/templates/complains/update.html
{% extends 'base.html' %}

{% block content %}
  <h1>UPDATE</h1>
  <hr>
  <form action="{% url 'complain:update' suggestion.pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
  <a href="{% url 'complain:detail' suggestion.pk %}">back</a>
{% endblock content %}