accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
]

manager/urls.py
from django.urls import path
from . import views


app_name = 'manager'
urlpatterns = [
    path('<username>/', views.index, name='index'),
    path('<username>/scanner/', views.scanner, name='scanner'),
    path('<username>/create/', views.create, name='create'),
]

safety_manager/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index),
    path('admin/', admin.site.urls),
    path('employee/', include('employee.urls')),
    path('manager/', include('manager.urls')),
    path('accounts/', include('accounts.urls')),
    path('suggestions/', include('suggestions.urls')),
    path('complain/', include('complain.urls'))
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <title>Document</title>
  </head>
  <body>
    <!-- 유효성 검증 통과 -->
    <nav class="d-flex flex-row m-3 justify-content-end align-items-center">
      {% if request.user.is_authenticated %}
        <div class="my-auto">
          <p class="h5 mb-0">안녕하세요, {{ user.name }} 님</p>
        </div>
        <div class="ms-4">
          <!-- 로그아웃 -->
          <form action="{% url 'accounts:logout' %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="로그아웃" class="btn btn-info"/>
          </form>
        </div>
        

        {% comment %}
        <!-- 회원 정보 수정 -->
        <a href="{% url 'accounts:update' %}">회원정보수정</a>

        <!-- 회원 정보 수정 -->
        <a href="{% url 'accounts:change_password' %}">비밀번호 변경</a>

        <!-- 회원 탈퇴 -->
        <form action="{% url 'accounts:delete' %}" method="POST">
          {% csrf_token %}
          <input type="submit" value="회원탈퇴" />
        </form>
        {% endcomment %}

      <!-- 유효성 검증 미통과 -->
      {% else %}
        <div>
          <a href="{% url 'accounts:login' %}">로그인</a>
        </div>
        <div class="ms-4">
          <a href="{% url 'accounts:signup' %}">회원가입</a>
        </div>
      {% endif %} 
    </nav>
    <hr>

    <div class="container">
      {% block content %} {% endblock content %}
    </div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/base_login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap" rel="stylesheet">
    <title>Document</title>
  </head>
  <body style="font-family: 'Noto Sans KR', sans-serif;">
    <!-- 유효성 검증 통과 -->
    <nav class="d-flex flex-row m-3 justify-content-end align-items-center">
      {% if request.user.is_authenticated %}
        <div class="my-auto">
          <p class="h5 mb-0">안녕하세요, {{ user.name }} 님</p>
        </div>
        <div class="ms-4">
          <!-- 로그아웃 -->
          <form action="{% url 'accounts:logout' %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="로그아웃" class="btn btn-info"/>
          </form>
        </div>
        

        {% comment %}
        <!-- 회원 정보 수정 -->
        <a href="{% url 'accounts:update' %}">회원정보수정</a>

        <!-- 회원 정보 수정 -->
        <a href="{% url 'accounts:change_password' %}">비밀번호 변경</a>

        <!-- 회원 탈퇴 -->
        <form action="{% url 'accounts:delete' %}" method="POST">
          {% csrf_token %}
          <input type="submit" value="회원탈퇴" />
        </form>
        {% endcomment %}

      <!-- 유효성 검증 미통과 -->
      {% else %}
        <div>
          <a href="{% url 'accounts:login' %}">로그인</a>
        </div>
        <div class="ms-4">
          <a href="{% url 'accounts:signup' %}">회원가입</a>
        </div>
      {% endif %} 
    </nav>
    <hr>

    <div>
      {% block content %} {% endblock content %}
    </div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <style>
        .quiz-container{
            position:relative;
            background-color:#f8f6f0;
            font-size:17px;
            color:#333;
            height:150px;
            margin-top:40px;
            text-align:center;
            font-weight:300;
        }
        
        .slide{
           position:absolute;
           left:0px;
           top:40px;
           width:100%;
           z-index:1;
           opacity:0;
           transition:opacity 0.5s;
        }
        
        .active-slide{
           opacity:1;
           z-index:2;
        }
    </style>
    <title>Document</title>
</head>
<body>
    <h1>근로자 출력등록2</h1>
    <div>
        <p>제3조(전도의 방지)</p>
        <p>#안전보건규칙 #제2장 #작업장 #전도 #청결 #근로자</p>
        <div class="quiz-container">
            <div id="quiz"> </div>
        </div>
        
        <div class="quiz-ctrl">
           <button id="previous" class="quiz-btn"> back </button>
           <button id="next" class="quiz-btn"> next </button>
           <button id="submit" class="quiz-btn"> 결과확인 </button>
           <div id="result"> </div>
        </div>
    </div>
    <a href="{% url 'accounts:login' %}" id="move" style="display: none;">출근 등록</a>

    <script>
        const quizData = [
            {
                question : '1. 사업주는 근로자가 작업장에서 넘어지거나 미끄러지는 등의 위험이 없도록 작업장 바닥등을 ___________로 유지하여야 한다.',
                answers : {
                    a : "안전하고 청결한 상태",
                    b : "정리되지 않고 더러운",
                },
                correct : 'a'
            },
            {
                question : '2. 사업주는 제품, 자재, 부재 등이 ___________ 붙들어 지탱하게 하는 등 안전 조치를 하여야 한다. 다만, 근로자가 접근하지 못하도록 조치한 경우에는 그러지 아니하다.',
                answers : {
                    a : "넘어질 수 있도록",
                    b : "넘어지지 않도록",
                },
                correct : 'b'
            },
        ]
        
        const quizDisplay = document.getElementById('quiz');
        const submitBtn = document.getElementById('submit');
        const previousBtn = document.getElementById('previous');
        const nextBtn = document.getElementById('next');

        let currentSlide = 0;
        const resultDisplay = document.getElementById('result');
        const moveDisplay = document.getElementById('move');
        
        function buildQuiz(){
            let output = [ ]; 
            quizData.forEach(  
                (currentQuestion, questionNum) => { 
                            const answers = [ ];     
                            for(item in currentQuestion.answers){  
                                        answers.push(`<label>
                                                        <input type="radio" name="question${questionNum}" value="${item}">
                                                            ${item} : ${currentQuestion.answers[item]}
                                                        </label>`);
                                }
                                    output.push(`<div class="slide"><div class="question"> ${currentQuestion.question}</div>
                                                <div class="answer">${answers.join('&nbsp;&nbsp;&nbsp;&nbsp;')}</div></div>`);
                            }              
            );
                quizDisplay.innerHTML = output.join('</br>');
            }
            
        function showResult(){
                const answerDisplays = quizDisplay.querySelectorAll('.answer');  
                let numCorrect = 0; 

                    quizData.forEach( (currentQuestion, questionNum)=>{
                        const answerDisplay = answerDisplays[questionNum]; 
                        const selector = `input[name=question${questionNum}]:checked`;  
                        const userAnswer = (answerDisplay.querySelector(selector) || {}).value;  


                            if(userAnswer === currentQuestion.correct){    
                                    numCorrect++;
                                    answerDisplays[questionNum].style.color = 'lightgreen';
                            }else{
                                    answerDisplays[questionNum].style.color = 'red';
                            }
                    });
                        
                    
                    submitBtn.style.display = 'none';
                    resultDisplay.innerHTML = `<h3 style="color:#333;">${quizData.length}개중에서 ${numCorrect}개 맞추셨습니다.</h3>`
                    if (numCorrect == 2) {
                        moveDisplay.style.display = 'block';
                    }
            }
        
            
        function showSlide(n){
            slides[currentSlide].classList.remove('active-slide');
            slides[n].classList.add('active-slide');
            currentSlide = n;
            if(currentSlide === 0){
                previousBtn.style.display = 'none';
            }else{
                previousBtn.style.display = 'inline-block';
            }
            if(currentSlide === slides.length-1){
                nextBtn.style.display = 'none';
                submitBtn.style.display = 'inline-block';
            }else{
                nextBtn.style.display = 'inline-block';
                submitBtn.style.display = 'none';
                    if(document.getElementById('retry')){
                            document.getElementById('retry').style.display = 'none';
                        }
                
            }
        }

        function showNextSlide(){  showSlide(currentSlide+1); }
        function showPreviousSlide(){ showSlide(currentSlide-1); }

        
        buildQuiz(); 
        const slides = document.querySelectorAll('.slide');
        showSlide(currentSlide);
        previousBtn.addEventListener('click',showPreviousSlide);
        nextBtn.addEventListener('click',showNextSlide);
        submitBtn.addEventListener('click',showResult);   
    </script>
</body>
</html>